### ISSUE TITLE
VoodooPS2Controller_v1.8.25.kext crash in Dell 7472 - i7, 16GB

### ISSUE THREAD

**Issue by ghost** [daliansky/dell7000#10]
For hackintosh in Dell 7472 (similar notebook), not install the kext (VoodooPS2Controller_v1.8.25.kext). This kext block the hackintosh. Other kext in the EFI work perfectly. 
(Only information)

**Comment by ghost** [comment]
Also worth to the Dell 7572

**Comment by mfakbar127** [comment]
so you dont install that kext, but you just put it at EFI folder ?

**Comment by ghost** [comment]
I deleted this kext in EFI folder and not installed this. 
It blocked my hackintosh and i installed all again. :-(

**Comment by dss862** [comment]
sleep wake problem catalina dell 7472 please help
