### ISSUE TITLE
Dell [7572 i5 8250u, sound and bluetooth not work]

### ISSUE THREAD

**Issue by indraAsLesmana** [daliansky/dell7000#4]
i have some issue with your latest commits.
- sound and bluetooth doesnt work, but wifi work (i used DW1560)

i try your latest release EFI (7x7x) 
- problem same,  sound and bluetooth doesnt work, but wifi work (i used DW1560)
- trackpad blank on preference 

i feel your lates release is very good impromvent on trackpad.

This how i install your EFI, please correct me if im wrong:
- mount EFI with clover configurator
- place your EFI
- run Kext Utility, (just run and quit after quit button enable)
- restart and select config to "config_MBP141.plist"

thanks.

**Comment by fanvinga** [comment]
Remove the USBinjectall.kext in kexts directory may solve the problem of Bluetooth.

**Comment by fanvinga** [comment]
Also if you are using 10.13.6 , install `BrcmPatchRam2.kext` and `BrcmFirmwareData.kext` to `/Library/Extensions` is necessary

**Comment by indraAsLesmana** [comment]
Thanks @fanvinga , Bluetooth work. how about sound?

**Comment by fanvinga** [comment]
Just try using other versions AppleALC.kext from [github release](https://github.com/acidanthera/AppleALC/releases) and keep injecting layout-id 56

**Comment by indraAsLesmana** [comment]
thank u work now with version 1.2.8, for sound problem.
