### ISSUE TITLE
[Dell 7572] Bluetooth and wifi interference issue on newest EFI

### ISSUE THREAD

**Issue by indraAsLesmana** [daliansky/dell7000#5]
I have your installer **macOS High Sierra 10.13.4(17E199) Installer with Clover 4418.dmg**, to install in my laptop.

**Testing with EFI default installer img**
clean install wifi and Bluetooth work instantly (internal speaker not work). I test Bluetooth to Bluetooth speaker, sound and wifi running great.

**Testing with new EFI**
If wifi on high Load, Bluetooth will laggy like mouse lag or sound lag to Bluetooth speaker. 

My laptop config:
- Dell 7572, i5 8250u 
- WIFI DW1560.
- macOS 10.13.6

for the first time, I assume is a hardware issue like described here https://www.tonymacx86.com/threads/bcm94352z-bluetooth-mouse-lag.216102/

but is not. is a configuration issue.
I will update this thread with video.

Thanks.

**Comment by fanvinga** [comment]
Try using 5.8Ghz wifi instead of 2.4Ghz wifi because the bluetooth of bcm nic usually subject to strong interference from 2.4G Wi-Fi

**Comment by indraAsLesmana** [comment]
I don't have 5ghz Wifi router, the problem is different EFI configuration effect interference.
can u suggest something to fix this problem?
this is 2 EFI i have:
EFI with interference issue:
https://drive.google.com/open?id=1CPlpImcIM8eCzoWmu8yQSP_6xrLYvHA7
EFI without interference issue:
https://drive.google.com/open?id=1OZws1zZ3MRvtA0Tn5mJ1mQt3jnhg41Va

**Comment by fanvinga** [comment]
Maybe you can try my clover :-D (Model:7472-1605 & DW1560)
[7472-20180826.zip](https://github.com/daliansky/dell7000/files/2326719/7472-20180826.zip

**Comment by achaheen** [comment]
I have the same issue with Dell XPS 9550 running Catalina. How did you solve this issue ?
